name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install PIP
      run: python -m pip install --upgrade 
      
    - name: Install package
      run: pip install -r requirements.txt
            
    - name: Test
      run: python -m pytest 
           
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my_ml_project:$(date +%s)
      
    
