name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test
        run: |
           python -m pytest 
           
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my_ml_project:$(date +%s)
      
    
