name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
               
    - name: Run unit test and build the Docker image
      run: docker build . --file model/Dockerfile --tag my_ml_project:$(date +%s)
      
    
